error: Make backoff streams infallible (#605)
error::Recover's Backoff stream type is fallible, but only because
this was required by the old API.

This change makes the backoff stream infallible.